config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :inputs
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/input.rb
class Input < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :inputs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/inputs_controller.rb
class InputsController < ApplicationController
  before_action :set_input, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:destroy]
  def index
    @inputs = Input.all
  end

  def show
  end

  def new
    # @input = Input.new
    @input = current_user.inputs.build
  end

  def edit
  end

  def create
    # @input = Input.new(input_params)
    @input = current_user.inputs.build(input_params)
    if isPrime?(@input[:number])
      @input[:prime_number] = true
      puts(@input[:prime_number])
    else
      @input[:prime_number] = false
      puts(@input[:prime_number])
    end

    respond_to do |format|
      if @input.save
        format.html { redirect_to @input, notice: "Input was successfully created." }
        format.json { render :show, status: :created, location: @input }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @input.errors, status: :unprocessable_entity }
      end
    end
  end

  def isPrime?(num)
    return if num <= 1
    (2..Math.sqrt(num)).none? { |i| (num % i).zero? }
  end

  def destroy
    @input.destroy
    respond_to do |format|
      format.html { redirect_to inputs_url, notice: "Input was successfully deleted." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @input = current_user.inputs.find_by(id: params[:id])
    redirect_to inputs_path, notice: "Not Authorized to make changes" if @input.nil?
  end

  private
    def set_input
      @input = Input.find(params[:id])
    end

    def input_params
      params.require(:input).permit(:number, :prime_number, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inputs_helper.rb
module InputsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <div class="container-fluid">
    <%= link_to 'Home', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, 
              class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Add Inputs", inputs_path, 
              class:"nav-link" %>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
          </li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<% if user_signed_in? %>
	<h1> Prime Number Engine</h1><br/>

	<h2> You are in! </h2>
<% else %>
	<h1> Prime Number Engine</h1><br/>

	<h2> Please sign up for an account to start your prime journey! </h2>
<% end %>

app/views/inputs/_form.html.erb
<%= form_with(model: input) do |form| %>
  <% if input.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(input.errors.count, "error") %> prohibited this input from being saved:</h2>

      <ul>
        <% input.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.label :number, class:"form-label" %>
    <%= form.number_field :number, class:"form-control w-25", placeholder:"number", required:'required' %>
  </div>

  <div class="field mb-3">
    <%= form.number_field :user_id, id: :input_user_id, value:current_user.id, type:"hidden" %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-secondary"%>
  </div>
<% end %>

app/views/inputs/edit.html.erb
<h1>Editing Input</h1>

<%= render 'form', input: @input %>

<%= link_to 'Show', @input, class:"btn btn-secondary" %>
<%= link_to 'Back', inputs_path, class:"btn btn-secondary" %>

app/views/inputs/index.html.erb
<h1>Table of Entries</h1>
<table class="table table-bordered table-striped table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Number</th>
      <th>Is it a Prime Number?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inputs.each do |input| %>
      <% if input.user == current_user %>
        <tr>
          <td><%= input.number %></td>
          <td><%= input.prime_number %></td>
          <td><%= link_to 'Destroy', input, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Input', new_input_path, class:"btn btn-secondary" %>

app/views/inputs/new.html.erb
<h1>New Input</h1>

<%= render 'form', input: @input %> <br/>

<%= link_to 'Back', inputs_path, class:"btn btn-secondary"%>

app/views/inputs/show.html.erb
<p>
  <strong>Number:</strong>
  <%= @input.number %>
</p>

<p>
  <strong>Is Prime Number: </strong>
  <%= @input.prime_number %>
</p>

<%= link_to 'Edit', edit_input_path(@input), class:"btn btn-secondary" %>
<%= link_to 'Back', inputs_path, class:"btn btn-secondary" %>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">

    <title>Ruby Prime Challenge</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <%= render 'home/header' %>
    <div class="container">
      <br/>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>

      <br/>
      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
  </body>
</html>